### ISSUE TITLE
Query over json instead of parsing text?

### ISSUE THREAD

**Issue by ratijas** [Nyr/wireguard-install#26]
The script uses **ip**(8) and **grep**(1) extensively. But the **ip**(8) family of commands supports json output via `-j` flag, which can be further operated on through **jq**(1) — command-line JSON processor.

If it would be alright to rely on existence of `jq` in `$PATH` (or at least on the ability to install it from repos on all supported systems), I think it would be feasible and more reliable to perform JSON queries rather than grepping plain text with repetitive and error-prone regexes.

For example, this first occurrence of ip|grep is the script:

```bash
if [[ $(ip -4 addr | grep inet | grep -vEc '127(\.[0-9]{1,3}){3}') -eq 1 ]]; then
  ip=$(ip -4 addr | grep inet | grep -vE '127(\.[0-9]{1,3}){3}' | cut -d '/' -f 1 | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}')
else
```

...could be replaced with this pipeline:

```bash
if [[ $(ip -j -4 addr | jq '[ .[].addr_info | .[].local | select(startswith("127.")|not) ] | length') -eq 1 ]]; then
  ip=$(ip -j -4 addr | jq -r '[ .[].addr_info | .[].local | select(startswith("127.")|not) ][0]')
else
```
And the second line is even shorter, indeed because there's actually less work to do — no need to count matches. They might be lengthier that grep variants on average, but just look at dat self-descriptiveness! I'm not a jq expert though, so there might be some space for improvements.

I'm willing to help and rewrite queries to jq.  Let's talk about it.

**Comment by ratijas** [comment]
Regarding that particular chunk of code.

1. I'd rather store `ip -j -4 addr` output in a local, and then parsed it twice. Just in case things might've changed between two `ip` invocations.
2. Also, I'm not sure if that's appropriate, but I'd also filter out `172.*/16` addresses which docker uses for internal networking bridges, and `10.*/8` subnet which is probably other VPN tunnels on the system.
    ```bash
    $ ip -j -4 addr | jq '[ .[].addr_info | .[].local | select(startswith("127.")|not) ] | length'
    9
    $ ip -j -4 addr | jq '[ .[].addr_info | .[].local | select(startswith("127.") or startswith("172.") or startswith("10.")|not) ] | length'
    1
    ```

**Comment by Nyr** [comment]
First of all, thanks a lot for being the change you want to see and offering to work on this instead of just demanding it.

While I agree that using a JSON parser is cleaner and simpler, it requires a tool not present by default in most systems and this is something which I try to avoid. The plain text grep is very reliable and has been thoroughly battle tested in [openvpn-install](https://github.com/Nyr/openvpn-install) for quite a while. Hours went into designing IP detection and management with some of the thought process not being obvious at first glance, but it is pretty solid with many weird situations considered.

It is not appropriate to filter out any private network as the installer fully supports configuring a VPN in a server behind NAT.

You can see other extreme examples of me trying to avoid installation of dependencies while making HTTP requests or managing PGP keys within the script. Indeed, one regret of mine was not being able to print the QR codes without the `qrencode` tool. Maybe in the future...

**Comment by ratijas** [comment]
Hi Nyr, thanks for detailed answer!

> it requires a tool not present by default in most systems and this is something which I try to avoid.

There are only so many officially supported systems. Would it be too bad to rely just on those few to get the tools we need? The **jq**(1) tool discussed here [isn't something exotic](https://stedolan.github.io/jq/download/) (not sure about CentOS though), and binary distributions exist, statically linked for 64-bit or 32-bit.

> Hours went into designing IP detection and management with some of the thought process not being obvious at first glance, but it is pretty solid with many weird situations considered.

I have no doubts there are many more hidden pitfalls which I may fail to spot at first sight. If anything, I'd like to know more about them, especially if they are not yet documented.

> It is not appropriate to filter out any private network as the installer fully supports configuring a VPN in a server behind NAT.

OK, that's fair.

> Maybe in the future...

LOL.  QR code in ASCII was pretty impressive. To this day I have no idea what to use it for, but still... impressive.

With that being said, given that "it works", I can totally understand why you are against the change.

Feel free to ping me back if you ever gonna change your mind. I'd rather prefer using robust maintainable software, than bare-bones grep-based but self-contained one.

**Comment by Nyr** [comment]
> There are only so many officially supported systems

Yes, but there are so many different images and custom templates from different service providers. It is a mess.

> ASCII was pretty impressive. To this day I have no idea what to use it for

Smartphones! WireGuard clients in Android and iOS can be configured just by scanning a code directly from your SSH session.
