### ISSUE TITLE
DNS leak

### ISSUE THREAD

**Issue by alexlii1971** [Nyr/wireguard-install#39]
Hello,

It seem not prevent DNS leak by now, and I followed several tutorial to prevent DNS leak,like this one https://www.ckn.io/blog/2017/11/14/wireguard-vpn-typical-setup/

 but always failed.

I just suppose that tutorials doe not work with this wireguard-install script, would you please let me know how to resovle, alternatively, a tutorial would be great appriecated.

Thanks

**Comment by Nyr** [comment]
A DNS leak is not an issue caused by this installer, it is a client-side configuration issue.

As long as the "DNS = xxx.xxx.xxx.xxx" parameter is correctly set in the client configuration file, that part is fine and you should check why your system is still using a different DNS server if that is the case.
