### ISSUE TITLE
Installer fails if port 22 is selected

### ISSUE THREAD

**Issue by apasov** [Nyr/wireguard-install#68]
Installer fails when user selects 22 as wireguard port. Generated QR code is invalid.
I think some ports like 22, 80 etc. must be forbidden and error message should say `Please select a different port` or something like that.

![image](https://user-images.githubusercontent.com/28765662/146637676-a9f047e4-9e24-4064-90c5-0f3819ee8ec6.png)

**Comment by adokitkat** [comment]
Port 22 is used by ssh protocol, 80 for http, etc. - they are already in use.

**Comment by apasov** [comment]
@adokitkat I'm aware what these ports are used for and would never use them for wireguard myself. But I showed this script to a non-technical guy who entered 22 as the port and got this error. I just think the script need some protection in such cases.

**Comment by KaeTuuN** [comment]
Maybe there could be a warning that Ports 22,123,443 or whatever are in use, since SSH could also be listening on another Port.
Quick and Dirty way to get all used Ports:
`netstat -tuln | awk -F":" '{print $2}' | awk -F" " '{printf $1" \n"}' | sort -n | uniq`
Downside: It needs netstat installed and looks ugly at the moment.

An Alternative could be to forbid Ports 1-1024 to, at least, lower the risk of handling errors.

**Comment by apasov** [comment]
@KaeTuuN I think it's overkill to get **all** used ports. We just need to check the one entered by the user.
It can be done with `lsof`  which unlike `netstat` doesn't need to be installed.
For example, if you need to check if port 22 is already in use you have to execute `lsof -i :22`
I submitted a PR.

**Comment by KaeTuuN** [comment]
My Intention was to show all used Ports before the User enters Port Number.
But just checking the one entered should be enough and is much easier, that's true!

**Comment by Nyr** [comment]
You can run SSH in port 22 TCP while WireGuard can simultaneously bind to 22 UDP.

In the attached photo, the user messed up somewhere else before running the script.

The linked pull request is also wrong for the same reason.
