### ISSUE TITLE
Peers can access ports on my server - Security Risk

### ISSUE THREAD

**Issue by afzl-wtu** [Nyr/wireguard-install#91]
I installed wireguard with your script. Everything is working fine. Issue I am facing is any peer device can access my web apps (on the server where wireguard is installed) like hestiacp at port 8083 and cockpit at port 9090 . By just typing 10.7.0.1:8083 in their browser they can also access it by typing 127.0.0.1:9090. This is a security risk. Peers can see everything in my private network on the server.

**Comment by Nyr** [comment]
Peers can only reach whatever services are listening in 10.7.0.1.

You can configure the services to not listen there.

**Comment by afzl-wtu** [comment]
> Peers can only reach whatever services are listening in 10.7.0.1.
> 
> You can configure the services to not listen there.

So this is this behaviour is by default by wireguard?
Can you please give any hint how to turn off this default behavior or how to turn off services listening on 10.7.0.1 interface.

**Comment by Nyr** [comment]
For example, in the case of Cockpit:
https://cockpit-project.org/guide/latest/listen

You would need to use the `ListenStream` parameter and set it to whatever IP address you want it to be listening on, instead of the default where only the port is configured, and it is listening on all IP addresses.

Similar configuration changes would need to be performed for any other software you are concerned about, it has nothing to do with WireGuard or this installer.
